### ISSUE TITLE
Token text is unsecure

### ISSUE THREAD

**Issue by SenpaiDesi** [KyzoCryptoboy/babaBot-discordBot#1]
Adding a global token var into your code that you have to replace every now and then with the "YOUR TOKEN HERE" text is dangerous when you make changes. Considering you can leave it in there by accident.

Suggestion:
- Get the token using venv
- add a json read method to load the token from a json file that you add to the .gitignore

**Comment by KyzoCryptoboy** [comment]
> Adding a global token var into your code that you have to replace every now and then with the "YOUR TOKEN HERE" text is dangerous when you make changes. Considering you can leave it in there by accident.
> 
> 
> 
> Suggestion:
> 
> - Get the token using venv
> 
> - add a json read method to load the token from a json file that you add to the .gitignore

Ja weet ik maar ik kijk nooit meer naar deze repo. Dus ik ga mijn token ook niet per ongelijk erin laten staan.

**Comment by SenpaiDesi** [comment]
Ah zo, dan laat ik je met rust haha
